// SPDX-FileCopyrightText: mpvQC developers
//
// SPDX-License-Identifier: GPL-3.0-or-later

pragma Singleton

import QtQuick

QtObject {
    readonly property url arrowDropDown: Qt.resolvedUrl("qrc:/data/icons/arrow_drop_down_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url aspectRatio: Qt.resolvedUrl("qrc:/data/icons/aspect_ratio_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url check: Qt.resolvedUrl("qrc:/data/icons/check_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url close: Qt.resolvedUrl("qrc:/data/icons/close_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url closeFullscreen: Qt.resolvedUrl("qrc:/data/icons/close_fullscreen_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url comment: Qt.resolvedUrl("qrc:/data/icons/comment_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url contentCopy: Qt.resolvedUrl("qrc:/data/icons/content_copy_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url delete_: Qt.resolvedUrl("qrc:/data/icons/delete_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url description: Qt.resolvedUrl("qrc:/data/icons/description_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url download: Qt.resolvedUrl("qrc:/data/icons/download_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url draft: Qt.resolvedUrl("qrc:/data/icons/draft_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url edit: Qt.resolvedUrl("qrc:/data/icons/edit_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url exitToApp: Qt.resolvedUrl("qrc:/data/icons/exit_to_app_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url fileExport: Qt.resolvedUrl("qrc:/data/icons/file_export_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url fileOpen: Qt.resolvedUrl("qrc:/data/icons/file_open_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url firstPage: Qt.resolvedUrl("qrc:/data/icons/first_page_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url folderOpen: Qt.resolvedUrl("qrc:/data/icons/folder_open_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url info: Qt.resolvedUrl("qrc:/data/icons/info_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboard: Qt.resolvedUrl("qrc:/data/icons/keyboard_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardArrowDown: Qt.resolvedUrl("qrc:/data/icons/keyboard_arrow_down_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardArrowLeft: Qt.resolvedUrl("qrc:/data/icons/keyboard_arrow_left_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardArrowRight: Qt.resolvedUrl("qrc:/data/icons/keyboard_arrow_right_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardArrowUp: Qt.resolvedUrl("qrc:/data/icons/keyboard_arrow_up_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardBackspace: Qt.resolvedUrl("qrc:/data/icons/keyboard_backspace_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardDoubleArrowRight: Qt.resolvedUrl("qrc:/data/icons/keyboard_double_arrow_right_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url keyboardReturn: Qt.resolvedUrl("qrc:/data/icons/keyboard_return_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url language: Qt.resolvedUrl("qrc:/data/icons/language_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url lastPage: Qt.resolvedUrl("qrc:/data/icons/last_page_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url minimize: Qt.resolvedUrl("qrc:/data/icons/minimize_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url movie: Qt.resolvedUrl("qrc:/data/icons/movie_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url movieEdit: Qt.resolvedUrl("qrc:/data/icons/movie_edit_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url musicNote: Qt.resolvedUrl("qrc:/data/icons/music_note_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url notes: Qt.resolvedUrl("qrc:/data/icons/notes_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url openInFull: Qt.resolvedUrl("qrc:/data/icons/open_in_full_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url palette: Qt.resolvedUrl("qrc:/data/icons/palette_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url playArrow: Qt.resolvedUrl("qrc:/data/icons/play_arrow_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url save: Qt.resolvedUrl("qrc:/data/icons/save_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url saveAs: Qt.resolvedUrl("qrc:/data/icons/save_as_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url search: Qt.resolvedUrl("qrc:/data/icons/search_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url select: Qt.resolvedUrl("qrc:/data/icons/select_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url selectCheckBox: Qt.resolvedUrl("qrc:/data/icons/select_check_box_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url settingsBackupRestore: Qt.resolvedUrl("qrc:/data/icons/settings_backup_restore_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url spaceBar: Qt.resolvedUrl("qrc:/data/icons/space_bar_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url subtitles: Qt.resolvedUrl("qrc:/data/icons/subtitles_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url title: Qt.resolvedUrl("qrc:/data/icons/title_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url tooltip2: Qt.resolvedUrl("qrc:/data/icons/tooltip_2_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url update: Qt.resolvedUrl("qrc:/data/icons/update_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url upload: Qt.resolvedUrl("qrc:/data/icons/upload_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
    readonly property url verticalSplit: Qt.resolvedUrl("qrc:/data/icons/vertical_split_24dp_1F1F1F_FILL0_wght400_GRAD0_opsz24.svg")
}
