# SPDX-FileCopyrightText: mpvQC developers
#
# SPDX-License-Identifier: MIT

set dotenv-load := true
set lazy := true

GIT_TAG := `git describe --tags --abbrev=0`
GIT_COMMIT := `git rev-parse HEAD | head -c 8`
GIT_IS_RELEASE := `git describe --exact-match HEAD > /dev/null 2>&1 && echo true || echo false`

alias fmt := format

@_default:
    just --list --unsorted

# Install dependencies and configure basic stuff
[group('dev')]
init ARGS='--group dev':
    #!/usr/bin/env bash
    uv sync {{ ARGS }}

    if [[ "{{ ARGS }}" == "--group dev" ]]; then
      QMLLS_INI=".qmlls.ini"
      echo "; Auto-generated by \`just init\`. Re-running \`just init\` overwrites this file." > "$QMLLS_INI"
      echo "[General]" >> "$QMLLS_INI"
      echo "DisableDefaultImports=false" >> "$QMLLS_INI"
      echo "no-cmake-calls=true" >> "$QMLLS_INI"
      SEP="{{ if os() == 'windows' { ';' } else { ':' } }}"
      echo "importPaths={{ justfile_directory() }}/qt/qml${SEP}{{ justfile_directory() }}" >> "$QMLLS_INI"
      echo "buildDir={{ justfile_directory() }}" >> "$QMLLS_INI"
      echo "just init: Created $QMLLS_INI ..."

      echo "Created by command: just init" > portable
      echo "Runs application in portable mode by storing all files in the <git-repo>/appdata directory" >> portable
      echo "just init: Configured portable mode ..."

      # Claude Code only discovers skills under .claude/skills, so symlink it
      mkdir -p .claude
      if [[ "{{ os() }}" == "windows" ]]; then
        [[ -e .claude/skills ]] || cmd //c mklink /J ".claude\\skills" ".agents\\skills" > /dev/null
      else
        ln -sfn ../.agents/skills .claude/skills
      fi
      echo "just init: Linked .claude/skills to .agents/skills ..."

      mkdir -p appdata/export-templates
      cp data/config/export-template.jinja appdata/export-templates/export-working.jinja
      echo '{{ '{{' }}' > appdata/export-templates/export-error.jinja
    fi

[group('dev')]
format *ARGS:
    uv run prek --config .config/prek.toml run --all-files {{ ARGS }}

[group('dev')]
update-python-dependencies:
    uv sync --upgrade
    just _update-dependency-versions
    bash build-aux/update-wayland-symbols.sh

[group('dev')]
update-git-hook-dependencies:
    uv run prek --config .config/prek.toml auto-update

# Stamp version info into data/build-info.toml
[group('build')]
set-build-info:
    uv run python build-aux/set_build_info.py \
        --tag '{{ GIT_TAG }}' \
        --commit '{{ GIT_COMMIT }}' \
        --is-release '{{ GIT_IS_RELEASE }}'
    cat data/build-info.toml

# Build full project into build/release
[group('build')]
@build: clean
    just build-develop
    mkdir -p build/release
    cp -r mpvqc build/release
    cp main.py build/release
    cp project.rcc build/release

# Build and compile resources into source directory
[group('build')]
@build-develop: _generate-qrc-file _update_pyproject_file
    uv run pyside6-project build
    uv run pyside6-rcc --binary project.qrc -o project.rcc
    grep -qxF 'depends QtQml.Models' io/github/mpvqc/mpvQC/Python/qmldir || echo 'depends QtQml.Models' >> io/github/mpvqc/mpvQC/Python/qmldir

# Remove ALL generated files
[group('build')]
@clean:
    find i18n -name "*.qm" -type f -delete
    find qt/qml -name "*.qmlc" -type f -delete
    rm -rf build io test/project.rcc testqml/project.rcc project.rcc test/rc_project.py testqml/rc_project.py rc_project.py project.json project.qrc

# Build release artifact (⚠️ modifies working tree)
[group('ci')]
build-release:
    #!/usr/bin/env bash
    set -euo pipefail
    function execute() { echo -e "\033[0;34m$*\033[0m"; "$@"; }
    execute rm -f .env
    execute find test testqml -mindepth 1 -delete
    execute find . -type f -name 'tst_*' -print -delete
    execute find . -type f -name 'TestHelpers.qml' -print -delete
    execute find . -type f -name '*Stub.qml' -print -delete
    execute export MPVQC_COMPILE_QML=true
    # The Flatpak build sets UV_NO_PROJECT, which makes --no-sync redundant and uv warns about it.
    if [[ -z "${UV_NO_PROJECT:-}" ]]; then
        execute export UV_NO_SYNC="1"
    fi
    execute export UV_OFFLINE="1"
    execute just set-build-info
    execute just build
    execute find build/release -type d -name "__pycache__" -print0 | xargs -0 rm -rf

# Recompile resources
[group('test')]
prepare-tests: build-develop
    rm -f test/rc_project.py testqml/rc_project.py
    cp project.rcc test/project.rcc
    cp project.rcc testqml/project.rcc

# Run Python and QML tests
[group('test')]
@test: prepare-tests test-python test-qml

[group('test')]
test-python *ARGS="build-aux test":
    QT_QPA_PLATFORM=offscreen uv run pytest {{ ARGS }}

# Run all QML tests, JOBS files at a time ('1' = single process)
[group('test')]
test-qml JOBS='auto':
    uv run -m testqml.runner --jobs '{{ JOBS }}'

# TARGET = file by name recursively matched under qt/qml
[group('test')]
test-qml-debug TARGET:
    uv run -m testqml.main --target '{{ TARGET }}'

# Lint QML files
[group('lint')]
@lint-qml: build-develop
    uv run pyside6-qmllint -I qt/qml -I . $(find qt/qml -type f -name '*.qml')

# Add language 'LOCALE' e.g. 'fr-FR' (ISO 639-1, ISO 3166-1)
[group('i18n')]
@add-translation LOCALE: _update_pyproject_file
    uv run pyside6-lupdate -source-language en-US -target-language {{ LOCALE }} -ts i18n/{{ LOCALE }}.ts
    just update-translations

# Update translation strings
[group('i18n')]
@update-translations: _update_pyproject_file _update_lupdate_project_file
    uv run pyside6-lupdate -locations none -project project.json

@_update_pyproject_file:
    uv run python build-aux/update_pyproject_file.py \
        --relative-to . \
        --include-directory qt/qml \
        --include-directory data \
        --include-directory mpvqc \
        --include-directory testqml \
        --include-directory i18n \
        --include-file main.py

_generate-qrc-file:
    #!/usr/bin/env bash

    if [[ "${MPVQC_COMPILE_QML}" == "true" ]]; then
      echo "Compiling QML files to cache..."
      find qt/qml -name "*.qml" -not -name "tst_*.qml" -type f | while read qml_file; do
        qmlc_file="${qml_file}c"
        echo "  Compiling $(basename "$qml_file")..."
        uv run pyside6-qmlcachegen --only-bytecode "$qml_file" -o "$qmlc_file" || exit 1
      done
      echo "  Removing .aotstats files..."
      find qt/qml -name "*.aotstats" -type f -delete
      echo "QML compilation complete!"
    else
      echo "Skipping QML cache generation. Can be enabled by setting env var MPVQC_COMPILE_QML=true"
    fi

    uv run python build-aux/generate-qrc-file.py \
        --relative-to . \
        --include-directory qt/qml \
        --include-directory data \
        --include-directory i18n \
        --out-file project.qrc

@_update_lupdate_project_file:
    uv run python build-aux/generate-lupdate-project-file.py \
        --relative-to . \
        --include-directory qt/qml \
        --include-directory mpvqc \
        --include-directory i18n \
        --include-file main.py \
        --out-file project.json

# Update dependency versions in build-info.toml
_update-dependency-versions:
    uv --offline export --no-hashes --no-annotate | uv run python build-aux/update_dependency_versions.py
