#!/usr/bin/env just --justfile

_default:
	just --list

# Prints relevant info for flatpak pypi dependencies
print:
	@python flatpak-pypi-checker.py \
		--dependency inject::none:any \
		--dependency PySide6-Essentials==6.7.3::manylinux:x86_64 \
		--dependency shiboken6==6.7.3::manylinux:x86_64 \
		--dependency MarkupSafe::cp312:manylinux:x86_64 \
		--dependency Jinja2::none:any \
		--dependency mpv::none:any | jq
