# SPDX-FileCopyrightText: mpvQC developers
#
# SPDX-License-Identifier: MIT

python-version = "3.13"
project-includes = ["../**/*.py*"]
search-path = [".."]
ignore-missing-imports = [
    "win32api",
    "win32con",
    "win32gui",
    "win32print",
]

[errors]
missing-override-decorator = "error"
