# Copyright 2024
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

_default:
	@just --list

generate-dark-colors DIRECTORY="~/Downloads":
	#!/usr/bin/env nu
	cd {{ DIRECTORY }}
		| ls -f -a *.json
		| sort-by modified
		| get name
		| each { |themeFile|
			open $themeFile
				| get "schemes"
				| get "dark" "dark-medium-contrast" "dark-high-contrast"
				| each { |variant|
					$variant
						| select "surfaceContainerLow" "onSurfaceVariant" "primaryContainer" "inversePrimary" "onSurface" "surfaceContainerHigh"
						| rename "background" "foreground" "control" "row-highlight" "row-highlight-text" "row-base-alternate"
				}
		 }
		 | flatten
		 | each { |row|
			 $row
			    | to toml
		 }
		 | str join "\n[[colors]]\n"

generate-light-colors DIRECTORY="~/Downloads":
	#!/usr/bin/env nu
	cd {{ DIRECTORY }}
		| ls -f -a *.json
		| sort-by modified
		| get name
		| each { |themeFile|
			open $themeFile
				| get "schemes"
				| get "light" "light-medium-contrast" "light-high-contrast"
				| each { |variant|
					$variant
						| select "surfaceContainerLow" "onSurfaceVariant" "secondary" "primary" "onPrimary" "surfaceContainerHighest"
						| rename "background" "foreground" "control" "row-highlight" "row-highlight-text" "row-base-alternate"
				}
		}
		| flatten
		| each { |row|
			 $row
			    | to toml
		}
		| str join "\n[[colors]]\n"
